version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget.exe restore UIMFLibrary.sln
build:
  project: UIMFLibrary.sln
  verbosity: minimal
test:
  categories:
    except:
    - PNL_Domain
artifacts:
- path: UIMFLibrary\bin\Release\net461\UIMFLibrary.dll
- path: UIMFLibrary\bin\Release\UIMFLibrary*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: Ggkz3LuVG+Bsykyisf0ptmatdvwIizkXhsPpPGSUW4B2y7XHuSAHMwJWk/ScGYSO
  skip_symbols: true
