version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget.exe restore UIMFLibrary.sln
build:
  project: UIMFLibrary.sln
  verbosity: minimal
test:
  categories:
    except:
    - PNL_Domain
artifacts:
- path: UIMFLibrary\bin\Release\net462\UIMFLibrary.dll
- path: UIMFLibrary\bin\Release\net472\UIMFLibrary.dll
- path: UIMFLibrary\bin\Release\netstandard2.0\UIMFLibrary.dll
- path: UIMFLibrary\bin\Release\UIMFLibrary*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: c2eqJoPSHlpzP5S292ju6zHplgXoduY8T1Xac3FyCO91zetL8c+fMTsekavxn8rH
  skip_symbols: true
